### ISSUE TITLE
Create a GOOD Dockerfile to build your image

### ISSUE THREAD

**Issue by HansiMou** [HansiMou/nyu-devops-BankingSystem#19]
Dockerfile is using [Best practices for writing Dockerfiles](https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/)

Use docker-compose to build images and link containers.

**Comment by np1535** [comment]
I have modified the vagrant file to use docker compose. Now, we should be able to run the server without having to login and manually run docker-compose.

**Comment by HansiMou** [comment]
Do we need to use docker-compose? I asked professor about this few days ago, he specifically mentioned that this is not involved in this homework.

**Comment by HansiMou** [comment]
Sorry, my fault. I don't know why I added that sentence. I think you can remove the docker-compose related code, to keep Dockerfile tight and small.
Also, as long as you can pass the unit and integration tests that we have, I think it is safe just to push to the master.

**Comment by np1535** [comment]
The docker-compose is useful to automate the server startup and linking of the docker containers which otherwise would require us to do it manually. Having the docker-compose is helpful in my understanding. I will keep it for now and we can discuss this in class and then decide whether we should remove it.
