### ISSUE TITLE
Set up DevOps Pipeline in Bluemix

### ISSUE THREAD

**Issue by HansiMou** [HansiMou/nyu-devops-BankingSystem#35]
- Set up the DevOps Pipeline in Bluemix to build and deploy your project when the master branch changes.

- Connect this DevOps pipeline to the GitHub repository for your project

- Add a Test Stage to the pipeline to run your integration tests

**Comment by np1535** [comment]
I would need administrator privilege so that I can set up the DevOps pipeline on Bluemix. I get the following error when I try to connect to the git repo from bluemix - 
The integration could not be set up. Check the settings and try again.
Reason: Unable to link without administrator privileges on the GitHub repository
